### ISSUE TITLE
defaultModsTransformation fails on line 420 when xpath expression returns multiple values

### ISSUE THREAD

**Issue by sdm7g** [uvalib/uva_fedora_transformations#7]
transform fails on this line when xpath expression returns more than one match:

https://github.com/uvalib/uva_fedora_transformations/blob/master/defaultModsTransformation.xsl#L420

This is resulting in sending incomplete malformed XML to SOLR. 

The general problem of passing thru bad XML has been filed as:
https://github.com/uvalib/tracksys/issues/194

**Comment by louffoster** [comment]
tracksys no longer produces solr for sirsi records - the defautModsTransform is no longer used
